### ISSUE TITLE
Error 500 after ataching .msg file to an issue.

### ISSUE THREAD

**Issue by saintxseiya** [alexbevi/redmine_msg_preview#1]
After attaching a .msg file to an issue this is the output in the logfile.

Processing IssuesController#show (for 217.67.37.200 at 2011-01-19 12:15:01) [GET]
  Parameters: {"action"=>"show", "id"=>"175", "controller"=>"issues"}
Rendering template within layouts/base
Rendering issues/show.rhtml

ActionView::TemplateError (undefined method `titlecase' for nil:NilClass) on line #21 of vendor/plugins/redmine_msg_preview/app/views/issues/_msg_list.html.erb:
18:   <% @issue.attachments.each do |att| %>
19:       <% msg = Mapi::Msg.open att.diskfile %>
20:     <tr class="<%= cycle("odd", "even") %>">
21:     <td><%= sender_to_s(msg) %></td>
22:       <td><%= msg.properties[0x0037] %></td>
23:       <td><%= format_time(msg.properties[0x3007].to_s) %></td>
24:       <td class="buttons">

```
vendor/plugins/redmine_msg_preview/init.rb:22:in `sender_to_s'
vendor/plugins/redmine_msg_preview/app/views/issues/_msg_list.html.erb:21
vendor/plugins/redmine_msg_preview/app/views/issues/_msg_list.html.erb:18
lib/redmine/hook.rb:113:in `send'
lib/redmine/hook.rb:113:in `view_issues_show_description_bottom'
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:144:in `call_hook'
app/views/issues/show.rhtml:63:in `_run_rhtml_app47views47issues47show46rhtml'
app/controllers/issues_controller.rb:116
app/controllers/issues_controller.rb:115:in `show'
```

Rendering /opt/bitnami/apps/redmine/public/500.html (500 Internal Server Error)

**Comment by alexbevi** [comment]
it looks like the sender is't being properly parsed from the msg. Can you forward me the actual msg file that you're trying to attach? (assuming it doen't contain any sensitive info?)

have you been able to attach anything successfully? maybe run a couple of tests and forward me any messages that aren't working so i can investigate further.

**Comment by saintxseiya** [comment]
i will try some others and report.

**Comment by saintxseiya** [comment]
Same result on different mails. I will forward an example for you.
