### ISSUE TITLE
500 Internal Server Error on opening closed issue

### ISSUE THREAD

**Issue by sandr** [alexbevi/redmine_msg_preview#2]
ActionView::TemplateError (OLE2 signature is invalid) on line #19 of vendor/plugins/redmine_msg_preview/app/views/issues/_msg_list.html.erb:
16:     </tr></thead>
17:     <tbody>
18:   <% @issue.attachments.each do |att| %>
19:       <% msg = Mapi::Msg.open att.diskfile %>
20:     <tr class="<%= cycle("odd", "even") %>">
21:     <td><%= lookup_property(msg, "SENDER") %></td>
22:       <td><%= lookup_property(msg, "SUBJECT") %></td>

```
vendor/plugins/redmine_msg_preview/app/views/issues/_msg_list.html.erb:19
vendor/plugins/redmine_msg_preview/app/views/issues/_msg_list.html.erb:18
lib/redmine/hook.rb:113:in `send'
lib/redmine/hook.rb:113:in `view_issues_show_description_bottom'
lib/redmine/hook.rb:63:in `send'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:63:in `each'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:60:in `tap'
lib/redmine/hook.rb:60:in `call_hook'
lib/redmine/hook.rb:144:in `call_hook'
app/views/issues/show.rhtml:63:in `_run_rhtml_app47views47issues47show46rhtml'
app/controllers/issues_controller.rb:117:in `show'
app/controllers/issues_controller.rb:116:in `show'
```

Rendering /x/x/x/redmine-1.1.1/public/500.html (500 Internal Server Error)

**Comment by alexbevi** [comment]
sandr, have you tried with any other msg attachments? I've found since writing this plugin that it's pretty unstable (due to the ruby-ole library) and it doesn't handle as many variations/versions of the MSG format as I would have liked :(
