### ISSUE TITLE
Possible Ruby 1.9 incompatibility

### ISSUE THREAD

**Issue by nroach** [alexbevi/redmine_msg_preview#3]
From server logs following addition of plugin (on boot, before any pages requested or attachments uploaded):

2012-06-12T15:52:00+00:00 app[web.1]: /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb:158:in `eval': /app/vendor/plugins/redmine_msg_preview/init.rb:21: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
2012-06-12T15:52:00+00:00 app[web.1]:         when "SENDER":
2012-06-12T15:52:00+00:00 app[web.1]:                       ^
2012-06-12T15:52:00+00:00 app[web.1]: /app/vendor/plugins/redmine_msg_preview/init.rb:23: syntax error, unexpected keyword_when, expecting keyword_end
2012-06-12T15:52:00+00:00 app[web.1]:         when "SUBJECT"
2012-06-12T15:52:00+00:00 app[web.1]:             ^
2012-06-12T15:52:00+00:00 app[web.1]:         when "CREATION_TIME"
2012-06-12T15:52:00+00:00 app[web.1]: /app/vendor/plugins/redmine_msg_preview/init.rb:25: syntax error, unexpected keyword_when, expecting keyword_end
2012-06-12T15:52:00+00:00 app[web.1]:             ^
2012-06-12T15:52:00+00:00 app[web.1]: /app/vendor/plugins/redmine_msg_preview/init.rb:31: syntax error, unexpected keyword_end, expecting $end
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/core_ext/kernel/reporting.rb:11:in`silence_warnings'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb:158:in `block in evaluate_init_rb'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb:48:in`load'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb:154:in `evaluate_init_rb'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/plugins/engines/lib/engines/plugin.rb:44:in`load'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin/loader.rb:38:in `block in load_plugins'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin/loader.rb:37:in`each'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/rails/plugin/loader.rb:37:in `load_plugins'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/initializer.rb:369:in`load_plugins'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/config/environment.rb:21:in `<top (required)>'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1
/gems/rails-2.3.14/lib/initializer.rb:113:in`run'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/initializer.rb:165:in `process'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in`require'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in `block in require'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:547:in`new_constants_in'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/rails-2.3.14/lib/commands/server.rb:84:in `<top (required)>'
2012-06-12T15:52:00+00:00 app[web.1]:   from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-2.3.14/lib/active_support/dependencies.rb:182:in`require'

**Comment by nroach** [comment]
Update:  Looks to be related to unhandled parser errors.  Issue is fixed by error-handling routines implemented in https://github.com/benizi/redmine_msg_preview.
